### ISSUE TITLE
help plz 

### ISSUE THREAD

**Issue by terexdev** [jieggii/mc.py#4]
File "C:\Users\User\Documents\-master\запаминалка-бот\generator.py", line 4, in <module>
    from mc import StringGenerator
ImportError: cannot import name 'StringGenerator' from 'mc' (C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mc\__init__.py)

**Comment by jieggii** [comment]
`StringGenerator`, начиная с версии `4.0.0`, был переименован в `PhraseGenerator`. 
Чтобы исправить ошибку, импортируйте `PhraseGenerator`, а не `StringGenerator`: `from mc import PhraseGenerator`; либо установите более старую версию **mc.py**: `pip install mc.py==3.1.1`
